Ch3 NumPy
====

ndarray数据类型
--------

In [1]:
import numpy as np

In [2]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int64')

In [8]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [9]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [10]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr1=np.array([1,2,3],dtype=np.float64)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2=np.array([1,2,3,4,5])
arr2.dtype

dtype('int64')

In [15]:
floatarr=arr2.astype(np.float64)
floatarr.dtype

dtype('float64')

In [16]:
arr=np.array([1.1,2.5,5.3,2.8])
arr.astype(np.int32)

array([1, 2, 5, 2], dtype=int32)

In [17]:
numeric_strings=np.array(['3.7','4.8','7.9'],dtype=np.string_)
# numeric_strings
numeric_strings.astype(float)

array([ 3.7,  4.8,  7.9])

In [18]:
int_array=np.array([1,2,3])
calibers=np.array([1.1,3.4],dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 1.,  2.,  3.])

In [19]:
empty_uint32=np.empty(8,dtype='u4')
empty_uint32

array([1412098008,      32526, 1412098008,      32526,   39452929,
           222208,   22757459,          0], dtype=uint32)

数组与标量的运算
------

In [20]:
arr=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
arr*arr


array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [21]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [22]:
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

简单的索引和切片
------

In [23]:
arr=np.arange(10)

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5:8]

array([5, 6, 7])

In [26]:
arr[:4]

array([0, 1, 2, 3])

In [27]:
arr[5:8]=12

In [28]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [29]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [30]:
arr_slice[1]=1234
arr_slice

array([  12, 1234,   12])

In [31]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [32]:
arr_slice[:]=1

In [33]:
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

In [34]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0][2]

3

In [35]:
arr2d[0,2]

3

In [36]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [37]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [39]:
old_values=arr3d[1].copy()

In [40]:
arr3d[1]=1
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [41]:
arr3d[1]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[0][1][2]

6

In [43]:
arr3d[0,1,2]

6

In [44]:
arr3d[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [45]:
arr[1:6]

array([1, 2, 3, 4, 1])

In [46]:
arr2d[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d[1,:2]

array([4, 5])

In [48]:
arr2d[:,1]

array([2, 5, 8])

布尔型索引
------

In [49]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [50]:
data

array([[ 2.25215829,  0.76630331, -0.24635815, -1.83649763],
       [ 1.09717554,  0.93554576,  0.54959334, -1.54084884],
       [-0.35182803, -1.09742671, -1.00506204, -1.11781733],
       [ 0.53558194, -1.07556976,  0.70306537, -1.65273378],
       [-1.48189943, -0.15823452, -1.65862326,  0.77909582],
       [ 0.16407502, -1.02541594, -0.79125333,  1.09305979],
       [-0.71865551,  0.16196491,  1.11002361,  0.17095177]])

In [51]:
names=='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [52]:
data[names=='Bob']

array([[ 2.25215829,  0.76630331, -0.24635815, -1.83649763],
       [ 0.53558194, -1.07556976,  0.70306537, -1.65273378]])

In [53]:
data[names=='Bob',2:]

array([[-0.24635815, -1.83649763],
       [ 0.70306537, -1.65273378]])

In [54]:
data[names=='Bob',3]

array([-1.83649763, -1.65273378])

In [55]:
data[names!='Bob']

array([[ 1.09717554,  0.93554576,  0.54959334, -1.54084884],
       [-0.35182803, -1.09742671, -1.00506204, -1.11781733],
       [-1.48189943, -0.15823452, -1.65862326,  0.77909582],
       [ 0.16407502, -1.02541594, -0.79125333,  1.09305979],
       [-0.71865551,  0.16196491,  1.11002361,  0.17095177]])

In [56]:
data[-(names=='Bob')]

array([[ 1.09717554,  0.93554576,  0.54959334, -1.54084884],
       [-0.35182803, -1.09742671, -1.00506204, -1.11781733],
       [-1.48189943, -0.15823452, -1.65862326,  0.77909582],
       [ 0.16407502, -1.02541594, -0.79125333,  1.09305979],
       [-0.71865551,  0.16196491,  1.11002361,  0.17095177]])

In [57]:
mask=(names=='Bob')|(names=='Joe')
data[mask]

array([[ 2.25215829,  0.76630331, -0.24635815, -1.83649763],
       [ 1.09717554,  0.93554576,  0.54959334, -1.54084884],
       [ 0.53558194, -1.07556976,  0.70306537, -1.65273378],
       [ 0.16407502, -1.02541594, -0.79125333,  1.09305979],
       [-0.71865551,  0.16196491,  1.11002361,  0.17095177]])

In [58]:
data[data<0]=0
data

array([[ 2.25215829,  0.76630331,  0.        ,  0.        ],
       [ 1.09717554,  0.93554576,  0.54959334,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.53558194,  0.        ,  0.70306537,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.77909582],
       [ 0.16407502,  0.        ,  0.        ,  1.09305979],
       [ 0.        ,  0.16196491,  1.11002361,  0.17095177]])

In [59]:
data[names=='Bob']=1
data

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.09717554,  0.93554576,  0.54959334,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.77909582],
       [ 0.16407502,  0.        ,  0.        ,  1.09305979],
       [ 0.        ,  0.16196491,  1.11002361,  0.17095177]])

花式索引
-----

In [60]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [61]:
arr[[4,3,0,1]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.]])

In [62]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [63]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [64]:
arr[[1,5,7,2],[1,2,3,0]]

array([ 5, 22, 31,  8])

In [65]:
arr[[1,5,7,2]][:,[1,2,3,0]]

array([[ 5,  6,  7,  4],
       [21, 22, 23, 20],
       [29, 30, 31, 28],
       [ 9, 10, 11,  8]])

In [66]:
arr[np.ix_([1,5,7,2],[1,2,3,0])]

array([[ 5,  6,  7,  4],
       [21, 22, 23, 20],
       [29, 30, 31, 28],
       [ 9, 10, 11,  8]])

数组转置和轴对称
-----

In [67]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [69]:
arr=np.random.randn(6,3)
np.dot(arr.T,arr)

array([[  5.57191683,   2.95121763,  -2.5798046 ],
       [  2.95121763,   7.37535227,   3.36792271],
       [ -2.5798046 ,   3.36792271,  10.95230704]])

In [70]:
arr=np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [71]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [72]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [74]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

通用函数
------

In [75]:
arr=np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [76]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [77]:
x=np.random.randn(8)
y=np.random.randn(8)
np.maximum(x,y)

array([-0.02864824, -0.57392652,  0.72572169,  0.72491132,  0.1468149 ,
        0.7765607 ,  0.81463853, -0.45561682])

In [78]:
arr=np.random.rand(7)*5
arr

array([ 2.32785865,  0.99027683,  0.47654879,  3.64560819,  2.08634258,
        4.63423768,  0.75667874])

In [79]:
np.modf(arr)

(array([ 0.32785865,  0.99027683,  0.47654879,  0.64560819,  0.08634258,
         0.63423768,  0.75667874]), array([ 2.,  0.,  0.,  3.,  2.,  4.,  0.]))

利用数组进行数据处理
-----------

In [80]:
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [81]:
import matplotlib.pyplot as plt
z=np.sqrt(xs**2+ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [82]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()
plt.title("Image plot of $\sqrt{x^2+y^2}$ for grid of values")
plt.show()

将条件逻辑表述为数组运算
-----

In [83]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [84]:
result=np.where(cond,xarr,yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [85]:
arr=np.random.randn(4,4)
np.where(arr>0,2,-2)

array([[-2, -2, -2, -2],
       [-2,  2, -2,  2],
       [ 2,  2, -2,  2],
       [-2, -2, -2, -2]])

In [86]:
np.where(arr>0,2,arr)

array([[-0.62550824, -0.70057092, -0.80329301, -1.49616161],
       [-0.06763791,  2.        , -0.55785067,  2.        ],
       [ 2.        ,  2.        , -1.0426127 ,  2.        ],
       [-0.96049572, -2.07281743, -0.11572975, -1.55381868]])

数学和统计方法
------------

In [87]:
arr=np.random.randn(5,4)
arr

array([[ 0.72890271,  1.41973944,  0.51586944,  0.22044788],
       [-0.25649104, -0.17286034,  0.98851765,  2.10157125],
       [ 0.95268162,  0.0187847 ,  1.11210241, -0.85020353],
       [-1.43635785, -1.0289911 , -1.4558205 ,  0.26671808],
       [ 0.23527127, -1.20861314, -0.06711564, -0.71244734]])

In [88]:
arr.mean()

0.068585299371408517

In [89]:
arr.sum()

1.3717059874281703

In [90]:
arr.mean(axis=0)

array([ 0.04480134, -0.19438809,  0.21871067,  0.20521727])

In [91]:
arr.cumsum(0)

array([[ 0.72890271,  1.41973944,  0.51586944,  0.22044788],
       [ 0.47241167,  1.2468791 ,  1.50438709,  2.32201914],
       [ 1.42509329,  1.2656638 ,  2.61648951,  1.47181561],
       [-0.01126456,  0.2366727 ,  1.16066901,  1.73853369],
       [ 0.22400671, -0.97194044,  1.09355337,  1.02608635]])

In [92]:
arr.cumsum(1)

array([[ 0.72890271,  2.14864216,  2.6645116 ,  2.88495948],
       [-0.25649104, -0.42935138,  0.55916627,  2.66073752],
       [ 0.95268162,  0.97146632,  2.08356874,  1.23336521],
       [-1.43635785, -2.46534896, -3.92116945, -3.65445137],
       [ 0.23527127, -0.97334187, -1.04045751, -1.75290485]])

In [93]:
arr.cumprod(1)

array([[ 0.72890271,  1.03485193,  0.53384849,  0.11768577],
       [-0.25649104,  0.04433713,  0.04382804,  0.09210774],
       [ 0.95268162,  0.01789584,  0.01990201, -0.01692076],
       [-1.43635785,  1.47799945, -2.1517019 , -0.5738978 ],
       [ 0.23527127, -0.28435194,  0.01908446, -0.01359667]])

用于布尔型数组的方法
-------------

In [94]:
arr=np.random.rand(100)
(arr>0).sum()

100

In [95]:
bools=np.array([False,True,True,False])
bools.any()

True

In [96]:
bools.all()

False

排序
-------------

In [97]:
arr=np.random.randn(8)
arr

array([-1.12102746,  0.77950852, -0.6743405 ,  0.56705638,  0.65498751,
       -0.45326371, -1.49506094, -1.75380189])

In [98]:
arr.sort()
arr

array([-1.75380189, -1.49506094, -1.12102746, -0.6743405 , -0.45326371,
        0.56705638,  0.65498751,  0.77950852])

In [99]:
arr=np.random.randn(5,3)
arr

array([[ 0.35946576, -0.0196478 ,  0.00361701],
       [-0.65417696,  0.01854077,  0.87664202],
       [ 0.87779684, -0.81057101,  1.09382327],
       [-1.98769051,  0.94253517, -1.31577094],
       [ 0.20029044, -1.01683268, -0.32916233]])

In [100]:
arr.sort(axis=0)
arr

array([[-1.98769051, -1.01683268, -1.31577094],
       [-0.65417696, -0.81057101, -0.32916233],
       [ 0.20029044, -0.0196478 ,  0.00361701],
       [ 0.35946576,  0.01854077,  0.87664202],
       [ 0.87779684,  0.94253517,  1.09382327]])

In [101]:
large_arr=np.random.randn(1000)
large_arr.sort()

In [102]:
large_arr[int(len(large_arr)*0.05)]

-1.5718393347251269

唯一化以及其他集合逻辑
---------

In [103]:
names=np.array(['Bob','Joe','Will','Will','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [104]:
ints=np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [105]:
values=np.array([6,0,0,3,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True,  True, False,  True], dtype=bool)

用于数组的文件输入输出
---------------

In [106]:
arr=np.arange(10)
np.save('some_array',arr)

In [107]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.savez('array_archive',a=arr,b=arr)

In [109]:
np.load('array_archive.npz')['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

存取文本文件
--------

线性代数
------

In [110]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [111]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [112]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [113]:
from numpy.linalg import inv,qr
X=np.random.randn(5,5)
mat=X.T.dot(X)

In [114]:
inv(mat)

array([[ 0.76075177, -0.28718302, -0.13991381, -0.01982303, -0.16104921],
       [-0.28718302,  0.73031527, -0.11897143,  0.22621661,  0.16800113],
       [-0.13991381, -0.11897143,  0.86341117, -0.03920336, -0.11070739],
       [-0.01982303,  0.22621661, -0.03920336,  0.19030623,  0.00847867],
       [-0.16104921,  0.16800113, -0.11070739,  0.00847867,  0.20022742]])

In [115]:
inv(mat).dot(mat)

array([[  1.00000000e+00,   5.55111512e-17,   8.32667268e-17,
          0.00000000e+00,   2.22044605e-16],
       [ -1.11022302e-16,   1.00000000e+00,  -2.77555756e-17,
         -3.88578059e-16,  -6.66133815e-16],
       [  8.32667268e-17,   1.11022302e-16,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [ -3.12250226e-17,   3.81639165e-17,   0.00000000e+00,
          1.00000000e+00,  -1.38777878e-17],
       [  0.00000000e+00,  -5.55111512e-17,   0.00000000e+00,
          1.11022302e-16,   1.00000000e+00]])

In [116]:
q,r=qr(mat)
r

array([[-2.60210955, -1.62239821, -1.27082468,  2.90316505, -3.97715687],
       [ 0.        , -5.09525596,  0.63733677,  9.2741455 ,  6.84651881],
       [ 0.        , -0.        , -1.22622589, -0.24583726, -1.21662868],
       [-0.        , -0.        ,  0.        , -3.86323083,  1.77061672],
       [ 0.        , -0.        ,  0.        , -0.        ,  3.063103  ]])

随机数生成
-----

In [117]:
samples=np.random.normal(size=(4,4))
samples

array([[-0.96997313, -0.69320615, -0.23478593, -0.17732249],
       [-0.51252115, -0.46692686,  1.23375145, -1.21965588],
       [ 1.83052644,  0.38322305, -0.40519856, -0.69702516],
       [-0.12358242, -0.02573241,  1.14643667,  0.23495032]])

In [118]:
from random import normalvariate
N=1000000
%timeit samples=[normalvariate(0,1) for _ in xrange(N)]

1 loops, best of 3: 1.32 s per loop


In [119]:
%timeit samples=np.random.normal(size=N)

10 loops, best of 3: 64.9 ms per loop


范例：随机漫步
-----------

In [133]:
import random
position=0
walk=[position]
steps=1000
for i in xrange(steps):
    step=1 if random.randint(0,1) else -1
    position+=step
    walk.append(position)

import matplotlib.pyplot as plt
plt.figure()
plt.plot(walk)
plt.xlabel('t')
plt.ylabel('walk')
plt.show()

In [136]:
nsteps=1000
draws=np.random.randint(0,2,size=nsteps)
steps=np.where(draws>0,1,-1)
walk=steps.cumsum()


import matplotlib.pyplot as plt
plt.figure()
plt.plot(walk)
plt.xlabel('t')
plt.ylabel('walk')
plt.show()

In [138]:
walk.min()

-12

In [141]:
walk.max()

64

In [143]:
max(walk)

64

In [147]:
(np.abs(walk)>=10).argmax()

11

In [163]:
nwalks=5000
nsteps=1000
draws=np.random.randint(0,2,size=(nwalks,nsteps))
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)
walks

array([[  1,   2,   3, ..., -22, -23, -24],
       [  1,   2,   1, ...,  -6,  -7,  -8],
       [ -1,  -2,  -1, ...,   4,   3,   4],
       ..., 
       [  1,   2,   3, ...,  -6,  -7,  -6],
       [  1,   0,  -1, ...,   6,   7,   8],
       [  1,   0,  -1, ...,  36,  37,  36]])

In [153]:
walks.max()
walk.min()

-12

In [166]:
hists30=(np.abs(walks)>=30).any(1)
hists30

array([ True, False, False, ..., False,  True,  True], dtype=bool)

In [157]:
hists30.sum()

3370

In [159]:
crossing_times=(np.abs(walks[hists30])>=30).argmax(1)
crossing_times.mean()

504.73531157270031

In [161]:
steps=np.random.normal(loc=0,scale=0.25,size=(nwalks,nsteps))

In [162]:
steps

array([[-0.23906049,  0.14545904, -0.25189923, ...,  0.02595781,
         0.11592384,  0.077817  ],
       [ 0.03415354,  0.03384556, -0.14634429, ..., -0.04452606,
        -0.34166118,  0.09721954],
       [ 0.51990122, -0.04516303, -0.21508818, ..., -0.3682145 ,
        -0.12851391,  0.22684407],
       ..., 
       [ 0.67313422, -0.32837224,  0.33997374, ..., -0.01741672,
         0.17865067, -0.03801761],
       [-0.24475884,  0.42292772, -0.43901114, ...,  0.15627191,
        -0.05618944,  0.09219917],
       [ 0.22607454, -0.16129651,  0.06228751, ..., -0.22227501,
         0.05618117, -0.36056066]])