In [1]:
from pandas import Series,DataFrame
import pandas as pd

pandas数据结构介绍
------

# series

In [2]:
obj=Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [5]:
obj2=Series([4,7,-5,3],index=['d','b','c','a'])

In [6]:
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [7]:
obj2.index

Index([u'd', u'b', u'c', u'a'], dtype='object')

In [8]:
obj2['b']

7

In [9]:
obj2['d']=8
obj2

d    8
b    7
c   -5
a    3
dtype: int64

In [10]:
obj2[['b','d']]

b    7
d    8
dtype: int64

In [11]:
obj2

d    8
b    7
c   -5
a    3
dtype: int64

In [12]:
obj2>2

d     True
b     True
c    False
a     True
dtype: bool

In [13]:
obj2[obj2>2]

d    8
b    7
a    3
dtype: int64

In [14]:
obj2*2

d    16
b    14
c   -10
a     6
dtype: int64

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [18]:
states=['California','Ohio','Oregon','Texas']
obj4=Series(sdata,index=states)
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [23]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [24]:
obj3+obj4

California       NaN
Ohio           70000
Oregon         32000
Texas         142000
Utah             NaN
dtype: float64

In [25]:
obj4.name='population'
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
Name: population, dtype: float64

In [26]:
obj4.index.name='state'
obj4

state
California      NaN
Ohio          35000
Oregon        16000
Texas         71000
Name: population, dtype: float64

In [27]:
obj.index=['Bob','Tom','Jeff','Reyn']
obj

Bob     4
Tom     7
Jeff   -5
Reyn    3
dtype: int64

# DataFrame

In [28]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
             'year':[2000,2001,2002,2001,2002],
             'pop':[1.5,1.7,3.6,2.4,2.9]}
frame=DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [29]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [30]:
frame2=DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [31]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [32]:
frame2.index

Index([u'one', u'two', u'three', u'four', u'five'], dtype='object')

In [33]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [34]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [35]:
frame2.ix['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [36]:
frame2['debt']=16.5

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [38]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
frame2['debt']=np.arange(5.)

In [40]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [41]:
val=Series([-1.2,-1.5,-1.7],index=['two','four','seven'])
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN

In [42]:
frame2['eastern']=frame2.state=='Ohio'
frame2


year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9   NaN   False

In [43]:
del frame2['eastern']
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [44]:
pop={'Nevada':{2000:100,2001:150,2002:300},'Ohio':{2000:130,2001:140,2005:250}}
frame3=DataFrame(pop)
frame3

Nevada  Ohio
2000     100   130
2001     150   140
2002     300   NaN
2005     NaN   250

In [45]:
frame3.T

2000  2001  2002  2005
Nevada   100   150   300   NaN
Ohio     130   140   NaN   250

In [46]:
DataFrame(pop,index=[2003,2004,2005])

Nevada  Ohio
2003     NaN   NaN
2004     NaN   NaN
2005     NaN   250

In [47]:
pdata={'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     100   130
2001     150   140
2002     NaN   NaN

In [48]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2000      100   130
2001      150   140
2002      300   NaN
2005      NaN   250

In [49]:
frame3.values

array([[ 100.,  130.],
       [ 150.,  140.],
       [ 300.,   nan],
       [  nan,  250.]])

In [50]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan]], dtype=object)

# 索引对象

In [51]:
obj=Series(range(3),index=['a','b','c'])
index=obj.index
index

Index([u'a', u'b', u'c'], dtype='object')

In [52]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [53]:
index['a']=1

TypeError: Index does not support mutable operations

In [54]:
index=pd.Index(np.arange(3))
obj2=Series([1.5,-2.5,0],index=index)
index

Int64Index([0, 1, 2], dtype='int64')

In [55]:
frame3

state  Nevada  Ohio
year               
2000      100   130
2001      150   140
2002      300   NaN
2005      NaN   250

In [56]:
'Ohio' in frame3.columns

True

In [57]:
2003 in frame3.index

False

基本功能
-----

# 重新索引

In [59]:
obj=Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [60]:
obj2=obj.reindex(['a','b','c','d','e','f'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
f    NaN
dtype: float64

In [61]:
obj.reindex(['a','b','c','d','e','f'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
f    0.0
dtype: float64

In [62]:
obj3=Series(['blue','purple','yellow'],index=[0,2,4])
obj3.reindex(np.arange(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [63]:
frame=DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [64]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a     0      1           2
b   NaN    NaN         NaN
c     3      4           5
d     6      7           8

In [65]:
frame.reindex(columns=['Ohio','Texas','California','Utah'])

Ohio  Texas  California  Utah
a     0      1           2   NaN
c     3      4           5   NaN
d     6      7           8   NaN

In [66]:
frame.reindex(columns=['Ohio','Texas','Utah'])

Ohio  Texas  Utah
a     0      1   NaN
c     3      4   NaN
d     6      7   NaN

In [67]:
frame.reindex(index=['a','b','c','d'],method='ffill',columns=['Ohio','Texas','California','Utah'])

Ohio  Texas  California  Utah
a     0      1           2   NaN
b     0      1           2   NaN
c     3      4           5   NaN
d     6      7           8   NaN

In [68]:
frame.ix[['a','b','c','d'],['Ohio','California','Texas','Utah']]

Ohio  California  Texas  Utah
a     0           2      1   NaN
b   NaN         NaN    NaN   NaN
c     3           5      4   NaN
d     6           8      7   NaN

In [69]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

# 丢弃指定轴上的项

In [70]:
obj=Series(np.arange(5.),index=['a','b','c','d','e'])
new_obj=obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: float64

In [71]:
new_obj.drop(['a','b'])

d    3
e    4
dtype: float64

In [72]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [73]:
data.drop('Ohio')

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data.drop(['one','two'],axis=1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

# 索引、选取和过滤

In [75]:
import numpy as np
obj=Series(np.arange(4.0),index=['a','b','c','d',])
obj

a    0
b    1
c    2
d    3
dtype: float64

In [76]:
obj['b']

1.0

In [77]:
obj[2]

2.0

In [78]:
obj[1:4]

b    1
c    2
d    3
dtype: float64

In [79]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: float64

In [80]:
obj[[1,3]]

b    1
d    3
dtype: float64

In [81]:
obj[obj<2]

a    0
b    1
dtype: float64

In [82]:
obj['b':'d']

b    1
c    2
d    3
dtype: float64

In [83]:
obj['b':'c']=5
obj

a    0
b    5
c    5
d    3
dtype: float64

In [84]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [86]:
data[['one','three']]

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [93]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [96]:
data[data>5]

one  two  three  four
Ohio      NaN  NaN    NaN   NaN
Colorado  NaN  NaN      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data[data<5]=1
data

one  two  three  four
Ohio        1    1      1     1
Colorado    1    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data.ix['Ohio',['one','two']]

one    1
two    1
Name: Ohio, dtype: int64

In [107]:
data.ix[['Ohio','Utah'],['one','two']]

one  two
Ohio    1    1
Utah    8    9

In [110]:
data.ix[['Ohio','Utah'],[1,3 ,2]]

two  four  three
Ohio    1     1      1
Utah    9    11     10

In [112]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [114]:
data.ix[:'Utah',:'two']

one  two
Ohio        1    1
Colorado    1    5
Utah        8    9

In [116]:
data.ix[data.three>5,:3]

one  two  three
Colorado    1    5      6
Utah        8    9     10
New York   12   13     14

In [119]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

# 算术运算和数据对齐

In [122]:
s1=Series([7.3,-2.5,3.4,1.5],index=['a','b','c','d'])
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [124]:
s1+s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [130]:
df1=DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df2=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [132]:
df1+df2

b   c   d   e
Colorado NaN NaN NaN NaN
Ohio       3 NaN   6 NaN
Oregon   NaN NaN NaN NaN
Texas      9 NaN  12 NaN
Utah     NaN NaN NaN NaN

In [134]:
df1.add(df2,fill_value=0)

b   c   d   e
Colorado  6   7   8 NaN
Ohio      3   1   6   5
Oregon    9 NaN  10  11
Texas     9   4  12   8
Utah      0 NaN   1   2

In [137]:
df1.reindex(columns=df2.columns,fill_value=0)

b  d  e
Ohio      0  2  0
Texas     3  5  0
Colorado  6  8  0

In [139]:
arr=np.arange(12.).reshape((3,4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [141]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [143]:
arr-arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [150]:
df2-df2.ix[0]

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [155]:
series2=Series(range(3),index=['b','e','f'])
df2+series2

b   d   e   f
Utah    0 NaN   3 NaN
Ohio    3 NaN   6 NaN
Texas   6 NaN   9 NaN
Oregon  9 NaN  12 NaN

In [157]:
series3=df2['d']
df2.sub(series3,axis=0)

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

# 函数应用和映射

In [162]:
frame=DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [163]:
frame

b         d         e
Utah    1.889140  0.196901 -1.347240
Ohio   -0.078014  2.677474 -0.583315
Texas  -0.768167  0.298349 -0.325006
Oregon -0.996449  1.087641 -1.461639

In [165]:
np.abs(frame)

b         d         e
Utah    1.889140  0.196901  1.347240
Ohio    0.078014  2.677474  0.583315
Texas   0.768167  0.298349  0.325006
Oregon  0.996449  1.087641  1.461639

In [169]:
f=lambda x:x.max()-x.min()

In [171]:
frame.apply(f)

b    2.885589
d    2.480573
e    1.136633
dtype: float64

In [173]:
frame.apply(f,axis=1)

Utah      3.236380
Ohio      3.260788
Texas     1.066515
Oregon    2.549280
dtype: float64

In [176]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -0.996449  0.196901 -1.461639
max  1.889140  2.677474 -0.325006

In [182]:
format=lambda x:'%.2f'%x
frame.applymap(format)

b     d      e
Utah     1.89  0.20  -1.35
Ohio    -0.08  2.68  -0.58
Texas   -0.77  0.30  -0.33
Oregon  -1.00  1.09  -1.46

In [184]:
frame['e'].map(format)

Utah      -1.35
Ohio      -0.58
Texas     -0.33
Oregon    -1.46
Name: e, dtype: object

# 排序和排名

In [187]:
obj=Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [191]:
frame=DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [193]:
frame.sort_index(axis=1,ascending=0)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [196]:
obj=Series([4,7,-3,2])
obj.order()

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: FutureWarning: order is deprecated, use sort_values(...)
  from ipykernel import kernelapp as app


2   -3
3    2
0    4
1    7
dtype: int64

In [199]:
frame=DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [202]:
frame.sort_values(by='a')

a  b
0  0  4
2  0 -3
1  1  7
3  1  2

In [204]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [208]:
obj=Series([7,-5,7,4,2,0,4])
#obj.rank(method='first')
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [210]:
obj.rank(method='first')

0    6
1    1
2    7
3    4
4    3
5    2
6    5
dtype: float64

In [212]:
obj.rank(ascending=False,method='max')

0    2
1    7
2    2
3    4
4    5
5    6
6    4
dtype: float64

In [215]:
frame=DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame.rank(axis=1)

a  b  c
0  2  3  1
1  1  3  2
2  2  1  3
3  2  3  1

# 带有重复值的轴索引

In [219]:
obj=Series(range(5),index=list('aabbc'))
obj.index.is_unique

False

In [221]:
obj['a']

a    0
a    1
dtype: int64

# 汇总和计算描述统计

In [223]:
df=DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [225]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [227]:
df.sum(axis=1)

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

In [230]:
df.sum(axis=1,skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [232]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [234]:
df.idxmax()

one    b
two    d
dtype: object

In [236]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [239]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [246]:
obj=Series(['a','b','c','d']*4)
obj.describe()

count     16
unique     4
top        d
freq       4
dtype: object

# 相关系数和协方差

In [249]:
import pandas.io.data as web
all_data={}
for ticket in ['AAPl','IBM','MSFT']:
    all_data[ticket]=web.get_data_yahoo(ticket,'1/1/2000','1/1/2010')
price=DataFrame({tic:data['Adj Close'] for tic,data in all_data.iteritems()})
volume=DataFrame({tic:data['Volume'] for tic,data in all_data.iteritems()})



In [267]:
volume

AAPl       IBM       MSFT
Date                                      
2000-01-03  133949200  10347700   53228400
2000-01-04  128094400   8227800   54119000
2000-01-05  194580400  12733200   64059600
2000-01-06  191993200   7971900   54976600
2000-01-07  115183600  11856700   62013600
2000-01-10  126266000   8540500   44963600
2000-01-11  110387200   7873300   46743600
2000-01-12  244017200   6803800   66532400
2000-01-13  258171200   8489700   83144000
2000-01-14   97594000  10956600   73416400
2000-01-18  114794400   7643900   81483600
2000-01-19  149410800   8634500   97568200
2000-01-20  457783200  17783400   56349800
2000-01-21  123981200   7868700   68416200
2000-01-24  110219200   6499200   63597600
2000-01-25  124286400   6936900   59823200
2000-01-26   91789600   4895100   49365000
2000-01-27   85036000   8324600   63654800
2000-01-28  105837200   6669400   58225400
2000-01-31  175420000   6202700   73194200
2000-02-01   79508800   7304700   70196600
2000-02-02  116048800   7707700   49915600
2000-02-03  118798400   6213800   49186000
2000-02-04  106330000   5405300   55365400
2000-02-07  110266800   5779500   40005800
2000-02-08  102160800   5464300   56229000
2000-02-09   74841200   5374700   55090000
2000-02-10   75745600   4446600   54527800
2000-02-11   53062800   5749400  115559000
2000-02-14   91884800   4544000   81028600
...               ...       ...        ...
2009-11-18   93580200   3970100   59431200
2009-11-19  135581600   5308400   51967700
2009-11-20  101666600   5354200   42647100
2009-11-23  118724200   7003500   41832700
2009-11-24   79609600   4816500   37341400
2009-11-25   71613500   3967700   32033500
2009-11-27   73814300   3319200   29357900
2009-11-30  106214500   6302700   44172000
2009-12-01  116440800   6578600   49904200
2009-12-02  178815000   4597900   36308600
2009-12-03  112179900   5760000   43095200
2009-12-04  206721200   7068500   58810700
2009-12-07  178689700   4144400   38082700
2009-12-08  172599700   5351400   37402200
2009-12-09  171195500   6071900   44713300
2009-12-10  122417400   7077800   45940200
2009-12-11  107443700   6597200   43744200
2009-12-14  123947600   5201300   34651200
2009-12-15  104864900   7862600   49473200
2009-12-16   88246200   6372500   55737800
2009-12-17   97209700   5909500   43691200
2009-12-18  152192600   9106600   94118000
2009-12-21  152976600   4772500   40129100
2009-12-22   87378900   5535500   36321000
2009-12-23   86381400   4127600   28362700
2009-12-24  125222300   4265100   11083900
2009-12-28  161141400   5800400   25384000
2009-12-29  111301400   4184200   29716200
2009-12-30  103021100   3867000   42006200
2009-12-31   88102700   4223400   31929700

[2515 rows x 3 columns]

In [269]:
returns=price.pct_change()
returns

AAPl       IBM      MSFT
Date                                    
2000-01-03       NaN       NaN       NaN
2000-01-04 -0.084311 -0.033944 -0.033780
2000-01-05  0.014634  0.035137  0.010544
2000-01-06 -0.086539 -0.017241 -0.033498
2000-01-07  0.047369 -0.004386  0.013068
2000-01-10 -0.017588  0.039648  0.007291
2000-01-11 -0.051151  0.008475 -0.025612
2000-01-12 -0.059973  0.004202 -0.032571
2000-01-13  0.109677 -0.010460  0.018901
2000-01-14  0.038114  0.011628  0.041159
2000-01-18  0.034847 -0.032393  0.027283
2000-01-19  0.025256  0.032397 -0.072087
2000-01-20  0.065103 -0.004184 -0.009346
2000-01-21 -0.019273  0.021008 -0.021226
2000-01-24 -0.045480  0.000000 -0.024096
2000-01-25  0.056471 -0.019547  0.015432
2000-01-26 -0.018374 -0.019937 -0.033435
2000-01-27 -0.001702 -0.027837 -0.006289
2000-01-28 -0.076136 -0.017070 -0.005063
2000-01-31  0.020910  0.006162 -0.003817
2000-02-01 -0.033735 -0.020045  0.051724
2000-02-02 -0.014339  0.031818 -0.020644
2000-02-03  0.045541  0.031938  0.027898
2000-02-04  0.045372 -0.012807  0.028347
2000-02-07  0.056134 -0.012973  0.000587
2000-02-08  0.007123  0.042169  0.031067
2000-02-09 -0.019587 -0.012099 -0.054008
2000-02-10  0.007769  0.014909  0.019231
2000-02-11 -0.041850 -0.031480 -0.057193
2000-02-14  0.064943  0.005959 -0.003127
...              ...       ...       ...
2009-11-18 -0.005024 -0.003732  0.003667
2009-11-19 -0.026461 -0.004760 -0.010960
2009-11-20 -0.002943 -0.004548 -0.005373
2009-11-23  0.029812  0.009767  0.010804
2009-11-24 -0.006994 -0.002106 -0.001002
2009-11-25 -0.001223 -0.005081 -0.004012
2009-11-27 -0.017631 -0.012414 -0.019134
2009-11-30 -0.003390  0.005171  0.006502
2009-12-01 -0.014707  0.012584  0.020401
2009-12-02 -0.003757 -0.005706 -0.007664
2009-12-03  0.001274  0.002673  0.001679
2009-12-04 -0.016083 -0.002352  0.005028
2009-12-07 -0.022605 -0.001650 -0.006337
2009-12-08  0.004869 -0.001889 -0.007385
2009-12-09  0.041765  0.012539  0.004734
2009-12-10 -0.006926  0.007399  0.005385
2009-12-11 -0.008960  0.002629 -0.000670
2009-12-14  0.011866  0.001928  0.008710
2009-12-15 -0.014265 -0.011083 -0.002989
2009-12-16  0.004429  0.001712  0.002665
2009-12-17 -0.016254 -0.010178 -0.016611
2009-12-18  0.018607  0.004003  0.025676
2009-12-21  0.014327  0.005785  0.005270
2009-12-22  0.010745  0.009949  0.009830
2009-12-23  0.008684  0.000539  0.003245
2009-12-24  0.034339  0.004385  0.002587
2009-12-28  0.012294  0.013326  0.005484
2009-12-29 -0.011861 -0.003477  0.007058
2009-12-30  0.012147  0.005461 -0.013699
2009-12-31 -0.004300 -0.012597 -0.015504

[2515 rows x 3 columns]

In [271]:
returns.MSFT.corr(returns.IBM)

0.49597970453869222

In [273]:
returns.MSFT.cov(returns.IBM)

0.00021595764429189563

In [278]:
returns.corr()

AAPl       IBM      MSFT
AAPl  1.000000  0.410011  0.424305
IBM   0.410011  1.000000  0.495980
MSFT  0.424305  0.495980  1.000000

In [280]:
returns.cov()

AAPl       IBM      MSFT
AAPl  0.001027  0.000252  0.000309
IBM   0.000252  0.000367  0.000216
MSFT  0.000309  0.000216  0.000516

In [282]:
returns.corrwith(returns.IBM)

AAPl    0.410011
IBM     1.000000
MSFT    0.495980
dtype: float64

In [284]:
returns.corrwith(volume)

AAPl   -0.057549
IBM    -0.007892
MSFT   -0.014245
dtype: float64

In [289]:
returns.IBM.corr(volume.IBM)

-0.0078916575491697616

# 唯一值、值计数以及成员资格

In [291]:
obj=Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [293]:
uniques=obj.unique()

In [295]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [297]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [301]:
pd.value_counts(obj,sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [307]:
mask=obj.isin(['b','c'])
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [309]:
data=DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [313]:
result=data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1    1    1    1
2    0    2    1
3    2    2    0
4    2    0    2
5    0    0    1

# 处理缺失数据

In [318]:
string_data=Series(['aardvark','artichoke',np.nan,'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [320]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [322]:
string_data[0]=None
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [324]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

滤除缺失数据
--------------

In [326]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [328]:
string_data.dropna()

1    artichoke
3      avocado
dtype: object

In [332]:
string_data[string_data.notnull()]

1    artichoke
3      avocado
dtype: object

In [334]:
data=DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3.]])
data

0    1   2
0   1  6.5   3
1   1  NaN NaN
2 NaN  NaN NaN
3 NaN  6.5   3

In [336]:
data.dropna()

0    1  2
0  1  6.5  3

In [338]:
data.dropna(how='all')

0    1   2
0   1  6.5   3
1   1  NaN NaN
3 NaN  6.5   3

In [342]:
data[4]=np.nan
data

0    1   2   4
0   1  6.5   3 NaN
1   1  NaN NaN NaN
2 NaN  NaN NaN NaN
3 NaN  6.5   3 NaN

In [344]:
data.ix[4]=np.nan
data

0    1   2   4
0   1  6.5   3 NaN
1   1  NaN NaN NaN
2 NaN  NaN NaN NaN
3 NaN  6.5   3 NaN
4 NaN  NaN NaN NaN

In [347]:
data.dropna(axis=0,how='all')

0    1   2   4
0   1  6.5   3 NaN
1   1  NaN NaN NaN
3 NaN  6.5   3 NaN

In [349]:
df=DataFrame(np.random.randn(7,3))
df.ix[:4,1]=np.nan;df.ix[:2,2]=np.nan
df

0         1         2
0  0.431850       NaN       NaN
1  1.928377       NaN       NaN
2  0.274535       NaN       NaN
3  0.070326       NaN -0.205946
4  0.736437       NaN  0.724577
5  0.382779 -1.534718 -0.363010
6  0.558921  0.733511  1.040409

In [351]:
df.dropna(thresh=3)

0         1         2
5  0.382779 -1.534718 -0.363010
6  0.558921  0.733511  1.040409

填充缺失数据
-----------

In [356]:
df.fillna(0)

0         1         2
0  0.431850  0.000000  0.000000
1  1.928377  0.000000  0.000000
2  0.274535  0.000000  0.000000
3  0.070326  0.000000 -0.205946
4  0.736437  0.000000  0.724577
5  0.382779 -1.534718 -0.363010
6  0.558921  0.733511  1.040409

In [359]:
df.fillna({1:0.5,2:-1})

0         1         2
0  0.431850  0.500000 -1.000000
1  1.928377  0.500000 -1.000000
2  0.274535  0.500000 -1.000000
3  0.070326  0.500000 -0.205946
4  0.736437  0.500000  0.724577
5  0.382779 -1.534718 -0.363010
6  0.558921  0.733511  1.040409

In [363]:
_=df.fillna(0,inplace=True)
df

0         1         2
0  0.431850  0.000000  0.000000
1  1.928377  0.000000  0.000000
2  0.274535  0.000000  0.000000
3  0.070326  0.000000 -0.205946
4  0.736437  0.000000  0.724577
5  0.382779 -1.534718 -0.363010
6  0.558921  0.733511  1.040409

In [365]:
df=DataFrame(np.random.randn(6,3))
df.ix[2:,1]=np.nan;df.ix[4:,2]=np.nan
df

0         1         2
0 -2.278425  0.675104  0.396848
1 -1.313494  0.962738 -0.940291
2  0.129525       NaN -0.448235
3  0.459196       NaN -0.132033
4  0.449010       NaN       NaN
5 -1.521321       NaN       NaN

In [367]:
df.fillna(method='ffill')

0         1         2
0 -2.278425  0.675104  0.396848
1 -1.313494  0.962738 -0.940291
2  0.129525  0.962738 -0.448235
3  0.459196  0.962738 -0.132033
4  0.449010  0.962738 -0.132033
5 -1.521321  0.962738 -0.132033

In [369]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -2.278425  0.675104  0.396848
1 -1.313494  0.962738 -0.940291
2  0.129525  0.962738 -0.448235
3  0.459196  0.962738 -0.132033
4  0.449010       NaN -0.132033
5 -1.521321       NaN -0.132033

In [372]:
data=Series([1,np.nan,3.5,np.nan,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

层次化索引
------

In [374]:
data=Series(np.random.randn(10),index=[list('aaabbbccdd'),[1,2,3,1,2,3,1,2,2,3]])
data

a  1   -0.606636
   2    0.787148
   3   -0.620120
b  1    0.151382
   2   -1.155864
   3    2.570254
c  1   -0.136961
   2   -0.407013
d  2    0.284226
   3   -0.186568
dtype: float64

In [376]:
data.index

MultiIndex(levels=[[u'a', u'b', u'c', u'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [378]:
data['b']

1    0.151382
2   -1.155864
3    2.570254
dtype: float64

In [380]:
data['b':'c']

b  1    0.151382
   2   -1.155864
   3    2.570254
c  1   -0.136961
   2   -0.407013
dtype: float64

In [382]:
data.ix[['b','d']]

b  1    0.151382
   2   -1.155864
   3    2.570254
d  2    0.284226
   3   -0.186568
dtype: float64

In [384]:
data[:,2]

a    0.787148
b   -1.155864
c   -0.407013
d    0.284226
dtype: float64

In [387]:
data.unstack()

1         2         3
a -0.606636  0.787148 -0.620120
b  0.151382 -1.155864  2.570254
c -0.136961 -0.407013       NaN
d       NaN  0.284226 -0.186568

In [389]:
data.unstack().stack()

a  1   -0.606636
   2    0.787148
   3   -0.620120
b  1    0.151382
   2   -1.155864
   3    2.570254
c  1   -0.136961
   2   -0.407013
d  2    0.284226
   3   -0.186568
dtype: float64

In [391]:
frame=DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [392]:
frame.index.names=['key1','key2']
frame.columns.names=['state','color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [395]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [397]:
frame.ix['a']

state  Ohio     Colorado
color Green Red    Green
key2                    
1         0   1        2
2         3   4        5

重排分级顺序
---------

In [400]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [408]:
frame.sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [411]:
frame.swaplevel(0,1).sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [416]:
frame.sum(level='key1')

state  Ohio     Colorado
color Green Red    Green
key1                    
a         3   5        7
b        15  17       19

In [418]:
frame.sum(level='color',axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

使用DataFrame的列
----------